[package]
name = "pg-pool-safe-query"
version = "0.1.0"
edition = "2021"
authors = ["JP Camara <48120+jpcamara@users.noreply.github.com>"]
license = "MIT"
publish = true

[dependencies]
pg_query = "0.7"
